### ISSUE TITLE
document contribution to window topic

### ISSUE THREAD

**Issue by zdarktknight** [derekgreene/dynamic-nmf#6]
Hi:
In the paper, it says: "3) A ranking of every MEPs contributions relative to all window and dynamic topics in the corpus"

Is there a function that out put this result? Or we need to calculate it by self.

**Comment by derekgreene** [comment]
This refers to MEP (author)-document counts for each window and dynamic topic. Since the MEP metadata was very specific to our application and database, the function is not included here.

Regards,
Derek.
